-- MySQL Script generated by MySQL Workbench
-- Sat Oct  3 11:30:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_project` ;

-- -----------------------------------------------------
-- Schema db_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_project` DEFAULT CHARACTER SET utf8mb4 ;
USE `db_project` ;

-- -----------------------------------------------------
-- Table `db_project`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_project`.`items` ;

CREATE TABLE IF NOT EXISTS `db_project`.`items` (
  `id` INT(8) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(1024) NOT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `filepath` VARCHAR(255) NOT NULL,
  `activation_status` ENUM('yes', 'no') NOT NULL DEFAULT 'yes',
  `item_count` INT(8) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_project`.`users` ;

CREATE TABLE IF NOT EXISTS `db_project`.`users` (
  `id` INT(8) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `username`, `password`, `email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_project`.`comments` ;

CREATE TABLE IF NOT EXISTS `db_project`.`comments` (
  `id` INT(8) NOT NULL,
  `commentator_name` VARCHAR(255) NOT NULL,
  `comment_text` VARCHAR(1024) NOT NULL,
  `rating` ENUM('1', '2', '3', '4', '5') NOT NULL,
  INDEX `fk_comments_items_idx` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_items`
    FOREIGN KEY (`id`)
    REFERENCES `db_project`.`items` (`id`)
    ON DELETE UPDATE
    ON UPDATE UPDATE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_project`.`categories` ;

CREATE TABLE IF NOT EXISTS `db_project`.`categories` (
  `category` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`items_and_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_project`.`items_and_categories` ;

CREATE TABLE IF NOT EXISTS `db_project`.`items_and_categories` (
  `id` INT(8) NOT NULL,
  `category` VARCHAR(255) NOT NULL,
  INDEX `fk_items_and_categories_items1_idx` (`id` ASC) VISIBLE,
  INDEX `fk_items_and_categories_categories1_idx` (`category` ASC) VISIBLE,
  CONSTRAINT `fk_items_and_categories_items1`
    FOREIGN KEY (`id`)
    REFERENCES `db_project`.`items` (`id`)
    ON DELETE UPDATE
    ON UPDATE UPDATE,
  CONSTRAINT `fk_items_and_categories_categories1`
    FOREIGN KEY (`category`)
    REFERENCES `db_project`.`categories` (`category`)
    ON DELETE UPDATE
    ON UPDATE UPDATE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_project`.`orders` ;

CREATE TABLE IF NOT EXISTS `db_project`.`orders` (
  `order_id` INT(8) NOT NULL AUTO_INCREMENT,
  `order_price` DECIMAL(6,2) NULL,
  `order_time` TIMESTAMP DEFAULT NOW() NOT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_project`.`payments` ;

CREATE TABLE IF NOT EXISTS `payments` (
 `id` int(6) NOT NULL AUTO_INCREMENT,
 `txnid` varchar(20) NOT NULL,
 `payment_amount` decimal(7,2) NOT NULL,
 `payment_status` varchar(25) NOT NULL,
 `itemid` varchar(25) NOT NULL,
 `createdtime` datetime NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
